<?php
//session_save_path("../temp");
	session_start();	
	unset($_SESSION['seller_name']);
	unset($_SESSION['seller_id']);
	unset($_SESSION['admin_id']);
	unset($_SESSION['admin_name']);
	//unset($_SESSION['timeout']);
	header("location:index.php");
